
SRC_DIR=./src
INC_DIR=./include

SRCS=   $(SRC_DIR)/loginwnd.c \
        $(SRC_DIR)/autoui.c

OBJS=$(SRCS:.c=.o)

TARGET=autoui

LIBSQL=libsqlite3.so
LIBSQL_DIR=/usr
LIBSQL_INC=$(LIBSQL_DIR)/include
LIBSQL_LIB=$(LIBSQL_DIR)/lib
LIBSQL_LDFLAGS=-L$(LIBSQL_LIB) -lsqlite3

LIBTEXU_N=libtexu.a
LIBTEXU_A=libtexu_a.a
LIBTEXU=$(LIBTEXU_A)
LIBTEXU_DIR=./TexU
LIBTEXU_INC=$(LIBTEXU_DIR)/include
LIBTEXU_LIB=$(LIBTEXU_DIR)/lib
LIBTEXU_LDFLAGS_N=-ltexu -L$(LIBTEXU_LIB) 
LIBTEXU_LDFLAGS_A=-ltexu_a -L$(LIBTEXU_LIB) 
LIBTEXU_LDFLAGS=$(LIBTEXU_LDFLAGS_A)


DFLAGS= -I. \
        -I$(INC_DIR) \
        -I$(LIBTEXU_INC) \
        -I$(LIBSQL_INC) 

CFLAGS=-m32 -g
#CFLAGS=-m32
OPTIONS = 
LDFLAGS = -L. -L.. -L./lib -L../lib -L/usr/local/lib -lpthread -lm -lz -lrt -lcurses -L/usr/lib $(LIBTEXU_LDFLAGS) $(LIBSQL_LDFLAGS) 

CC=gcc
BIN=Linux_3.10.0-1062.el7.x86_64
INSTALL_DIR=../lib
SOURCE_DIR=.
DEPENDFLAGS=-D__UNIX__ -D__LINUX__ -DUSE_TCL_AUTOMATION
#DEPENDFLAGS=-D__UNIX__ -D__LINUX__ 


DEFINES  = $(CFLAGS) $(OPTIONS) $(DFLAGS) $(DEPENDFLAGS)
LINK_DEFINES  = $(CFLAGS) $(OPTIONS) $(DFLAGS) $(LDFLAGS)

.PHONY: default all clean

default: $(TARGET)

all: default

%.o: %.c
	$(CC) $(DEFINES) -c $< -o $@
    

$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LINK_DEFINES)
    
clean:
	rm -f *.o  $(TARGET) $(OBJS) core a.out

depend:
	makedepend -- $(DEPENDFLAGS) $(CFLAGS) -- $(SRCS) 
# DO NOT DELETE

